### PR TITLE
fix: throw exception if Github repository URL is invalid

### LINKED ISSUE #100: Setup fails at setupTravis(), info.ghrepo is undefined
```bash
? Are you using GitHub Enterprise? No
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? incendiary
? What is your GitHub username? DJTB
? What CI are you using? Travis CI
ERR! semantic-release TypeError: Cannot read property 'slug' of undefined
ERR! semantic-release     at /home/subrosa/.config/yarn/global/node_modules/semantic-release-cli/dist/lib/travis.js:90:68
ERR! semantic-release     at Generator.next (<anonymous>)
ERR! semantic-release     at step (/home/subrosa/.config/yarn/global/node_modules/semantic-release-cli/dist/lib/travis.js:113:191)
ERR! semantic-release     at /home/subrosa/.config/yarn/global/node_modules/semantic-release-cli/dist/lib/travis.js:113:361
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! semantic-release  TypeError: Cannot read property 'slug' of undefined
ERR! semantic-release     at /home/subrosa/.config/yarn/global/node_modules/semantic-release-cli/dist/lib/travis.js:90:68
ERR! semantic-release     at Generator.next (<anonymous>)
ERR! semantic-release     at step (/home/subrosa/.config/yarn/global/node_modules/semantic-release-cli/dist/lib/travis.js:113:191)
ERR! semantic-release     at /home/subrosa/.config/yarn/global/node_modules/semantic-release-cli/dist/lib/travis.js:113:361
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:103:7)
```

line 90 is 
```js
travis.repoid = _.get((yield promisify(travis.repos(info.ghrepo.slug[0], info.ghrepo.slug[1]).get.bind(travis))()), 'repo.id');
```

package.json
```js
"repository": {
    "type": "git",
    "url": "https://github.com/DJTB/KanaWana/"
  },
```

New access tokens have appeared on both of my npm and github accounts.

If I `console.log(info)` in setupTravis I can see my npm and git usernames, password, access tokens. The github repo url is present too, but there is no key for ghrepo.

I have a travis account and I manually toggled the repo.
image

Any help would be appreciated, keen to use sr-cli!

### PR DESCRIPTION
**Pull request by KalleV**
If the Github URL could not be parsed and an Enterprise Github URL is not provided,
exit CLI with an error instead of assigning a null value to info.ghrepo.slug.

Fixes #100

### CODE REVIEW

File: src/lib/repository.js [hunk 1]
```diff
@@ -63,7 +63,8 @@ module.exports = async function(pkg, info) {
       },
     ]);
     info.ghepurl = answers.url;
-    return;
+    if (answers.enterprise) return;
+    throw new Error('Invalid GitHub repository URL');
```
Comment (gr2m) [inline src/lib/repository.js]: I think this error might be confusing? If I answer the the enterprise question with no, then the "Invalid GitHub repository URL" error will get thrown? Is that intended? Or am I missing something?

Comment (KalleV) [reply src/lib/repository.js]: @gr2m How about a different error message such as: "Failed to detect a valid Github repository URL. Please verify your configuration."? Currently, if you answer "no" to the Github Enterprise prompt when your project contains an invalid Git URL, a null value for the parsed repository URL is passed all the way to the CI-specific configuration stage (https://github.com/semantic-release/cli/blob/master/src/index.js#L86) before failing with the TypeError mentioned in #100.

Comment (gr2m) [reply src/lib/repository.js]: sounds like the problem is the statement above:

```js
info.ghepurl = answers.url;
```

Maybe wrapping it in an if block where we check if the enterprise question was answered with yes?

```js
if (answers.enterprise) {
  info.ghepurl = answers.url
}
```

Comment (KalleV) [reply src/lib/repository.js]: The assignment causing the TypeError is `info.ghrepo = {slug: parsedUrl};` (https://github.com/semantic-release/cli/blob/master/src/lib/repository.js#L69) since `parsedUrl` is still null after the GitHub Enterprise prompt if you answer `no`.

Comment (gr2m) [reply src/lib/repository.js]: Ah okay now I understand. A better error message will do then, maybe add the `repoUrl` to the message?

```js
throw new Error(`GitHub repository URL is invalid: ${repoUrl}`)
```

Comment (KalleV) [reply src/lib/repository.js]: Sure

**Comment by gr2m** [comment]
Thanks Kalle!
