### PR TITLE
fix(npm): various fixes to the cli npm logic

### LINKED ISSUE #18: Use existing publishConfig registry setting during setup
eg:

``` json
"publishConfig": {
  "registry": "https://my-private-npm.com"
}
```

### LINKED ISSUE #60: NPM url validation is a little too eager
We use internal urls for our registry that don't resolve publicly. Example: `http://npm-registry.internal1`. Unfortunately it's impossible to enter these right now because the `isURL` rejects them. Would it be okay to add `require_tld: false` to the `isURL` options?

### LINKED ISSUE #79: Authentication with Artifactory Online (private npm) doesn't work
I'm trying to setup semantic-release against a private npm package hosted on Artifactory (not the npm public registry), but it fails for me:

```
? Is the GitHub repository private? Yes
? What is your npm registry? https://<customer>.artifactoryonline.com/<customer>/api/npm/blaze-npm-releases/
? What is your npm username? <username>
? What is your npm email? <email>
? What is your npm password? **************************************
ERR! semantic-release Could not login to npm registry. Check your credentials.
ERR! semantic-release Error: 204 Could not create user
ERR! semantic-release undefined
ERR! semantic-release     at /Users/ghengeveld/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/npm-registry-client/lib/adduser.js:112:17
ERR! semantic-release     at /Users/ghengeveld/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/npm-registry-client/lib/adduser.js:73:16
ERR! semantic-release     at f (/Users/ghengeveld/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/once/once.js:17:25)
ERR! semantic-release     at /Users/ghengeveld/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/npm-registry-client/lib/request.js:68:16
ERR! semantic-release     at f (/Users/ghengeveld/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/once/once.js:17:25)
ERR! semantic-release     at RegClient.<anonymous> (/Users/ghengeveld/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/npm-registry-client/lib/request.js:255:12)
ERR! semantic-release     at Request._callback (/Users/ghengeveld/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/npm-registry-client/lib/request.js:170:14)
ERR! semantic-release     at Request.self.callback (/Users/ghengeveld/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/request/request.js:200:22)
ERR! semantic-release     at emitTwo (events.js:87:13)
ERR! semantic-release     at Request.emit (events.js:172:7)
ERR! semantic-release  [Error: 204 Could not create user
ERR! semantic-release undefined]
```

I'm confident the credentials are correct. In fact connecting directly to Artifactory proves this.

`curl -u<username> https://<customer>.artifactoryonline.com/<customer>/api/npm/auth`

That prompts me for the password and gives me back an auth token and the associated email address. 

I've also tried the base64 encoded password and the auth token. Note that my `~/.npmrc` is already setup to correctly handle publishing to Artifactory (for scoped packages) and I have the publishConfig registry setup in package.json too, so I'm a bit surprised semantic-release-cli doesn't just pick that up.

On a related note I think failing to enter the right password should not exit the wizard but provide the option to try again.

### LINKED ISSUE #107: Unable to setup with a custom registry run by `sinopia`
I'm trying to publish my package to a local registry because I don't want it actually published anywhere, I just want the features of the changelog, plugins, tag and all that. 😛 

I tried yesterday with an Adobe CouchDB local server, but it gave me the same error.

This is what I ran (username is `user` and password is `pass` :P)

```sh
semantic-release-cli setup
? Are you using GitHub Enterprise? No
? What is your npm registry? http://localhost:4873
? What is your npm username? user
? What is your npm password? ****
```

Here's the error:
```js
Error: this user already exists : -/user/org.couchdb.user:user
ERR! semantic-release     at makeError (~/.config/yarn/global/node_modules/npm-registry-client/lib/request.js:304:12)
ERR! semantic-release     at RegClient.<anonymous> (~/.config/yarn/global/node_modules/npm-registry-client/lib/request.js:292:14)
ERR! semantic-release     at Request._callback (~/.config/yarn/global/node_modules/npm-registry-client/lib/request.js:212:14)
ERR! semantic-release     at Request.self.callback (~/.config/yarn/global/node_modules/request/request.js:186:22)
ERR! semantic-release     at emitTwo (events.js:106:13)
ERR! semantic-release     at Request.emit (events.js:192:7)
ERR! semantic-release     at Request.<anonymous> (~/.config/yarn/global/node_modules/request/request.js:1081:10)
ERR! semantic-release     at emitOne (events.js:96:13)
ERR! semantic-release     at Request.emit (events.js:189:7)
ERR! semantic-release     at IncomingMessage.<anonymous> (~/.config/yarn/global/node_modules/request/request.js:1001:12)
ERR! semantic-release     at Object.onceWrapper (events.js:291:19)
ERR! semantic-release     at emitNone (events.js:91:20)
ERR! semantic-release     at IncomingMessage.emit (events.js:186:7)
ERR! semantic-release     at endReadableNT (_stream_readable.js:974:12)
ERR! semantic-release     at _combinedTickCallback (internal/process/next_tick.js:74:11)
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:98:9)
```

And here's the Sinopia log, if useful.
```sh
 http  <-- 409, user: undefined, req: 'PUT /-/user/org.couchdb.user:user', error: this user already exists
 http  <-- 409, user: undefined, req: 'PUT /-/user/org.couchdb.user:user', error: this user already exists
```

I don't understand why it is a problem that the user exists, as I'm guessing all you need credentials for is to login and then push to the registry.

### PR DESCRIPTION
**Pull request by kbrandwijk**
Fixes 4 open issues regarding npm logic. Please see individual commits for details.

Fixes #60, fixes #107, fixes #18, fixes #79.

### CODE REVIEW

**Comment by pvdlg** [comment]
I didn't look in detail, but for info we are using one commit per feature/fix and not a work log type. So we get a clean commit history.

So for example commit like `style: linting` should be squashed with the commit in which the linting error were introduced.

See http://www.bitsnbites.eu/git-history-work-log-vs-recipe/ for more details

Also for simplicity, whenever possible, it's better to open multiple more specific so it's easier to review (maybe it's not relevant regarding this PR)

**Comment by kbrandwijk** [comment]
To be honest, if I create a new branch to fix some issues, I'm not going to submit 4 PR's and create 4 new branches in 2 hours time. I changed the PR description after I discovered I forgot to lint, because the argument of a clean commit history didn't apply anymore because of that. The title and description are now updated to allow squashing.

File: src/lib/npm.js [hunk 1]
```diff
@@ -23,9 +23,17 @@ async function getNpmToken({npm, options}) {
...
-  const {token} = await promisify(client.request.bind(client, uri))({method: 'PUT', body});
+  const { err, token } = await client.requestAsync(uri, {method: 'PUT', body } ).catch(
+    err => { 
+      // Some registries (Sinopia) return 409 for existing users, retry using authenticated call
+      if (err.code = 'E409') {
+        return client.requestAsync(uri, { authed: true, method: 'PUT', auth: { username: npm.username, password: npm.password }, body })
+          .catch(err => ({ err }))
+      }
+    }
+  )
```
Comment (gr2m) [inline src/lib/npm.js]: 👍

File: src/lib/npm.js [hunk 2]
```diff
@@ -42,13 +42,27 @@ async function getNpmToken({npm, options}) {
...
+  if (pkg.name[0] !== '@') return conf.get('registry') || 'https://registry.npmjs.org/'
+    
+  const scope = pkg.name.split('/')[0]
+  const scopedRegistry = conf.get(`${scope}/registry`)
+
+  if (scopedRegistry) return scopedRegistry
+
+  return conf.get('registry') || 'https://registry.npmjs.org/'
+
+}
```
Comment (gr2m) [inline src/lib/npm.js]: code looks good, but moving forward we really need to improve the test / code coverage situation :)

File: src/lib/npm.js [hunk 3]
```diff
@@ -67,6 +69,14 @@ module.exports = async function(pkg, info) {
         require_tld: false, // eslint-disable-line camelcase
       }),
     },
+    {
+      type: 'list',
+      name: 'authmethod',
+      message: 'Which authentication method is this npm registry using?',
+      choices: [{name: 'Token based', value: 'token'}, {name: 'Legacy', value: 'legacy'}],
```
Comment (gr2m) [inline src/lib/npm.js]: maybe clarify what `Legacy` means, like `'Legacy (username & password)`'? Maybe it’s clear enough, I can’t tell, as I’ve never run into it myself

Comment (pvdlg) [reply src/lib/npm.js]: If we clarify what legacy is we should mention username, password and email, as email is required.

Comment (kbrandwijk) [reply src/lib/npm.js]: Updated

File: src/lib/npm.js (hunk 2 above)
Comment (kbrandwijk) [reply src/lib/npm.js]: Agreed

File: src/lib/npm.js [hunk 4]
```diff
@@ -42,14 +41,31 @@ async function getNpmToken({npm, options}) {
   log.info('Successfully created npm token.');
 }
 
+function getRegistry(pkg, conf) {
```
Comment (pvdlg) [inline src/lib/npm.js]: Where do we use that in semantic-release to retrieve the registry?

AFAK we use https://github.com/semantic-release/npm/blob/master/lib/get-registry.js and its the only place where we read the registry

File: src/lib/npm.js [hunk 5]
```diff
@@ -25,22 +22,65 @@ async function getNpmToken({npm, options}) {
...
   const uri = url.resolve(npm.registry, '-/user/org.couchdb.user:' + encodeURIComponent(npm.username));
-  const {err, token} = await client.requestAsync(uri, {method: 'PUT', body}).catch(err => {
-    // Some registries (Sinopia) return 409 for existing users, retry using authenticated call
-    if (err.code === 'E409') {
-      return client
-        .requestAsync(uri, {authed: true, method: 'PUT', auth: {username: npm.username, password: npm.password}, body})
-        .catch(err => ({err}));
-    }
+
+  const {err, token} = await new Promise(resolve => {
```
Comment (pvdlg) [inline src/lib/npm.js]: Why changing to a callback call here?
You could use `async/await` instead:
```js
let err;
let token;
try {
({err, token} = await client.requestAsync(uri, {method: 'PUT', body}));
} catch (err) {
if (err.code === 'E409') {
....
} else if (....) {
....
}

```

File: src/lib/npm.js [hunk 6]
```diff
@@ -25,22 +22,65 @@ async function getNpmToken({npm, options}) {
...
+    validate: answer => validateToken(answer, uri, body, npm),
+  });
+}
+
+async function validateToken(otp, uri, body, npm) {
+  if (!validator.isNumeric(otp)) {
+    return false;
+  }
+
+  return new Promise(resolve => {
```
Comment (pvdlg) [inline src/lib/npm.js]: Same here, you could use `async/await` for consistency and clarity.

File: src/lib/npm.js (hunk 5 above)
Comment (kbrandwijk) [reply src/lib/npm.js]: The reason for using a callback is that Promises (either directly or through promisify) don't support getting multiple arguments back on failure. Only `err` is accessible. I need response.headers too. So the only way is to use the callback, and wrap it myself.

File: src/lib/npm.js (hunk 6 above)
Comment (kbrandwijk) [reply src/lib/npm.js]: Here, the same thing applies. There are cases where no error is returned, but response.body.ok == false. I can't check that without access to response, which again requires the callback.

File: src/lib/npm.js (hunk 5 above)
Comment (pvdlg) [reply src/lib/npm.js]: Ah good point. For info you can solve that by using [pify with the multiargs](https://github.com/sindresorhus/pify#multiargs) option.
But that would be something for another PR

File: src/lib/npm.js (hunk 4 above)
Comment (pvdlg) [reply src/lib/npm.js]: That's super old, it's not in the code base anymore.
We should use https://github.com/semantic-release/npm/blob/master/lib/get-registry.js for consistency.

But that can be done in a different PR. Let me know if you prefer to do it here, otherwise I can merge this PR

File: src/lib/npm.js (hunk 5 above)
Comment (kbrandwijk) [reply src/lib/npm.js]: I searched for a lot of libraries, including bluebird and es6-promisify, but they both support multiArgs only on success, not on error. Thank you for pointing me at this, I will create an issue for it.

File: src/lib/npm.js (hunk 4 above)
Comment (kbrandwijk) [reply src/lib/npm.js]: There's no runtime dep on semantic-release yet. Is there any way to reuse this, without copying?

Comment (pvdlg) [reply src/lib/npm.js]: It's in a plugin so not easily.
It's only 2 lines of code and it uses [registry-auth-token](https://github.com/rexxars/registry-auth-token), so I guess it ok.
